<?php

return [
  'Base Line' => [
    '_color' => ['sh'=>'#0b5394','bh'=>'#6FA8DC','to'=>'#CFE2F3'],
  	'_cols' => [
      [
        'Computer Science' => [
          'Algoritmos' => [],
          'Estructura de Datos' => [],
          'Complejidad Algorítmica' => [],
          'Paradigmas de Programación' => [],
          'Sistemas Distribuidos' => [],
        ],
        'Software Engineering' => [
          'POO' => [],
          'Principios SOLID' => [],
          'Patrones de Diseño' => [],
          'Dependency Injection' => [],
          'Code Smells' => [],
        ],
        'Methodology' => [
          'Agile Software Development' => [],
          'Scrum' => [],
          'Kanban' => [],
          'SAFe' => [],
        ],
      ],
  	],
  ],
  'Profile Specific' => [
    '_color' => ['sh'=>'#134F5C','bh'=>'#76A5AF','to'=>'#D0E0E3'],
    '_cols' => [
      [
        'Web Back End' => [
          'Java' => [],
          'Lenguajes Back End' => [],
          'Spring Framework' => [],
          'Frameworks Back End' => [],
          'HTTP' => [],
          'Sesiones' => [],
          'Cookies' => [],
          'Forms' => [],
          'REST' => [],
          'Javascript Server Side' => [],
          'Config Management' => [],
          'File Systems' => [],
          'Mailing' => [],
          'Memory Management' => [],
          'Character Encoding' => [],
          'Persistencia de Datos' => [],
          'Textual Search' => [],
          'Error Handling' => [],
        ],
      ],
      [
        'Web Front End' => [
          'HTML' => [],
          'CSS' => [],
          'CSS Preprocessor' => [],
          'CSS Frameworks' => [],
          'JS' => [],
          'JS Frameworks' => [],
          'JS Transpilers' => [],
          'JS Task Runners' => [],
          'JS Server Side Package Manager' => [],
          'JS Browser Package Manager' => [],
          'HTML5 Web Storage' => [],
          'HTML5 Web Sockets' => [],
          'HTML5 Web Workers' => [],
          'HTML5 Forms' => [],
          'HTML5 Notification' => [],
          'HTML5 Web Components' => [],
          'Front End UX/UI' => [],
          'Responsive Design/Media Query' => [],
        ],
      ],
      [
        'Mobile' => [
          'HIG' => [],
          'Mobile UX/UI' => [],
          'Android SDK / Swift / Objective-C' => [],
          'Hardware Device API' => [],
          'Battery Optimization' => [],
          'Mobile Security' => [],
        ],
        'Data Scientist' => [
          'Relational DBs' => [],
          'NoSQL DB Types' => [],
          'SQL' => [],
          'DB De/Normalization' => [],
          'ACID Properties' => [],
          'Hadoop' => [],
          'R / Python / Scala' => [],
          'Machine Learning' => [],
          'Neo4j' => [],
          'Spark' => [],
        ],
      ],
      [
        'Architect' => [
          'Web Application Architecture' => [],
          'MVC Architecture' => [],
          'Cloud Computing' => [],
          'Streams' => [],
          'Event-Driven Architecture' => [],
          'Queues' => [],
          'Serverless Architecture' => [],
          'Enterprise Architecture Frameworks' => [],
          'Microservices' => [],
          'UML' => [],
        ],
        'QA' => [
          'Testing' => [],
          'Automated Unit Testing' => [],
          'Automated Functional Testing' => [],
          'Mocking' => [],
          'Cucumber / Jacoco' => [],
          'Stress Testing' => [],
        ],
      ],
    ],
  ],
  'Cross Profile' => [
    '_color' => ['sh'=>'#85200c','bh'=>'#cc4125','to'=>'#f7dac9'],
    '_cols' => [
      [
        'Security' => [
          'Authentication Methods' => [],
          'OWASP' => [],
          'SSL / TLS' => [],
          'Cryptography' => [],
          'Password Handling' => [],
          'Public Key Infrastructure' => [],
        ],
        'Networking' => [
          'OSI Model' => [],
          'DNS' => [],
          'TCP / IP' => [],
        ],
        'SysAdmin' => [
          'Linux' => [],
          'Docker' => [],
          'IaC Tools' => [],
          'SSH' => [],
          'Cron' => [],
        ],
      ],
      [
        'DevOps' => [
          'GIT' => [],
          'Dependency management Tool' => [],
          'Continuous integration' => [],
          'Jenkins' => [],
          'Binary Repository Server' => [],
          'Release Management' => [],
          'Static Code Analysis' => [],
          'Nagios / Splunk / Dynatrace' => [],
        ],
        'Performance Optimization & Scaling' => [
          'Database Scaling Strategies' => [],
          'Back End Optimization' => [],
          'Front End Optimization' => [],
          'Cache' => [],
          'Table Indexing' => [],
          'DB Clustering' => [],
          'DB Sharding' => [],
          'SQL Tunning' => [],
        ],
      ],
    ],
  ],
];

