<?php

return [

  'profiles' => [
    'Back End Software Engineer',
    'Front End Software Engineer',
    'Mobile Software Engineer',
    'QA Engineer',
    'Data Scientist',
    'Architect',
  ],
  'seniorities' => ['Junior','Semi-Senior','Senior'],
  'skills' => [
    'Base Line' => [
      '_color' => ['sh'=>'#0b5394','bh'=>'#6FA8DC','to'=>'#CFE2F3'],
    	'_cols' => [
        [
          'Computer Science' => [
            'Algoritmos' => '223,112,112,111,233,223',
            'Estructura de Datos'=>'223,112,112,111,233,223',
            'Complejidad Algorítmica' => '112,111,111,000,222,222',
            'Paradigmas de Programación' => '122,111,112,000,112,122',
            'Sistemas Distribuidos' => '113,111,112,000,123,123',
          ],
          'Software Engineering' => [
            'POO' => '233,233,233,122,233,233',
            'Principios SOLID' => '233,123,123,001,012,223',
            'Patrones de Diseño' => '123,123,123,011,012,223',
            'Dependency Injection' => '123,123,123,011,012,223',
            'Code Smells' => '012,012,012,001,012,123',
          ],
          'Methodology' => [
            'Agile Software Development' => '123,123,123,123,123,123',
            'Scrum' => '123,123,123,123,123,123',
            'Kanban' => '123,123,123,123,123,123',
            'SAFe' => '123,123,123,123,123,123',
          ],
        ],
    	],
    ],
    'Profile Specific' => [
      '_color' => ['sh'=>'#134F5C','bh'=>'#76A5AF','to'=>'#D0E0E3'],
      '_cols' => [
        [
          'Web Back End' => [
            'Java' => [],
            'Lenguajes Back End' => [],
            'Spring Framework' => [],
            'Frameworks Back End' => [],
            'HTTP' => [],
            'Sesiones' => [],
            'Cookies' => [],
            'Forms' => [],
            'REST' => [],
            'Javascript Server Side' => [],
            'Config Management' => [],
            'File Systems' => [],
            'Mailing' => [],
            'Memory Management' => [],
            'Character Encoding' => [],
            'Persistencia de Datos' => [],
            'Textual Search' => [],
            'Error Handling' => [],
          ],
        ],
        [
          'Web Front End' => [
            'HTML' => [],
            'CSS' => [],
            'CSS Preprocessor' => [],
            'CSS Frameworks' => [],
            'JS' => [],
            'JS Frameworks' => [],
            'JS Transpilers' => [],
            'JS Task Runners' => [],
            'JS Server Side Package Manager' => [],
            'JS Browser Package Manager' => [],
            'HTML5 Web Storage' => [],
            'HTML5 Web Sockets' => [],
            'HTML5 Web Workers' => [],
            'HTML5 Forms' => [],
            'HTML5 Notification' => [],
            'HTML5 Web Components' => [],
            'Front End UX/UI' => [],
            'Responsive Design/Media Query' => [],
          ],
        ],
        [
          'Mobile' => [
            'HIG' => [],
            'Mobile UX/UI' => [],
            'Android SDK / Swift / Objective-C' => [],
            'Hardware Device API' => [],
            'Battery Optimization' => [],
            'Mobile Security' => [],
          ],
          'Data Scientist' => [
            'Relational DBs' => [],
            'NoSQL DB Types' => [],
            'SQL' => [],
            'DB De/Normalization' => [],
            'ACID Properties' => [],
            'Hadoop' => [],
            'R / Python / Scala' => [],
            'Machine Learning' => [],
            'Neo4j' => [],
            'Spark' => [],
          ],
        ],
        [
          'Architect' => [
            'Web Application Architecture' => [],
            'MVC Architecture' => [],
            'Cloud Computing' => [],
            'Streams' => [],
            'Event-Driven Architecture' => [],
            'Queues' => [],
            'Serverless Architecture' => [],
            'Enterprise Architecture Frameworks' => [],
            'Microservices' => [],
            'UML' => [],
          ],
          'QA' => [
            'Testing' => [],
            'Automated Unit Testing' => [],
            'Automated Functional Testing' => [],
            'Mocking' => [],
            'Cucumber / Jacoco' => [],
            'Stress Testing' => [],
          ],
        ],
      ],
    ],
    'Cross Profile' => [
      '_color' => ['sh'=>'#85200c','bh'=>'#c77767','to'=>'#f7dac9'],
      '_cols' => [
        [
          'Security' => [
            'Authentication Methods' => [],
            'OWASP' => [],
            'SSL / TLS' => [],
            'Cryptography' => [],
            'Password Handling' => [],
            'Public Key Infrastructure' => [],
          ],
          'SysAdmin' => [
            'Linux' => [],
            'Docker' => [],
            'IaC Tools' => [],
            'SSH' => [],
            'Cron' => [],
          ],
          'Networking' => [
            'OSI Model' => [],
            'DNS' => [],
            'TCP / IP' => [],
          ],
        ],
        [
          'DevOps' => [
            'GIT' => [],
            'Dependency management Tool' => [],
            'Continuous integration' => [],
            'Jenkins' => [],
            'Binary Repository Server' => [],
            'Release Management' => [],
            'Static Code Analysis' => [],
            'Nagios / Splunk / Dynatrace' => [],
          ],
          'Performance Optimization & Scaling' => [
            'Database Scaling Strategies' => [],
            'Back End Optimization' => [],
            'Front End Optimization' => [],
            'Cache' => [],
            'Table Indexing' => [],
            'DB Clustering' => [],
            'DB Sharding' => [],
            'SQL Tunning' => [],
          ],
        ],
      ],
    ],
  ],
];

